DiT:
  depth: 1
  hidden_size: 512
  patch_size: 1
  num_heads: 4
  in_channels: 2
  input_size: 1
  num_classes: 2

SimpleMLPAdaLN:
  in_channels: 2
  model_channels: 512
  out_channels: 4
  z_channels: 1
  num_res_blocks: 2